<?
$PERM["buyer-office"]["6"]="W";
$PERM["buyer-office"]["*"]="D";
$PERM["sales-office"]["7"]="X";
$PERM["sales-office"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>